<a href="https://colab.research.google.com/github/AbhilashGaurav/Algobulls_internship_assessment/blob/main/Algobull_internship.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### # Installing all the dependencies

In [ ]:
pip install plotly

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: plotly in /usr/local/lib/python3.8/dist-packages (5.5.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.8/dist-packages (from plotly) (8.2.0)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from plotly) (1.15.0)

In [ ]:
pip install requests

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests) (2022.12.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests) (1.24.3)

**1.**Define a Class ScriptData which can fetch US Stock data using Alpha Vantage.
[Use this link to get your FREE API Key].
The class should implement the following methods:
**a.** fetch_intraday_data: (method arguments: script)
Fetches intraday data for given “script” (Example for script: “GOOGL”,
“AAPL”) and stores as it is.

**b.** **convert_intraday_data:** (method arguments: script)
Converts fetched intraday data (in point a.) as a pandas DataFrame
(hereafter referred as “df”) with the following columns: 

i. timestamp (data type: pandas.Timestamp)

ii. open (data type: float)

iii. high (data type: float)

iv. low(data type: float)

v. close (data type: float)

vi. volume (data type: int)

**c.** **Additional methods for overloading the following operations:**

i. getitem

ii. setitem

iii. contains

________________________________________________________________________________

### # Class with functionlaity request in the point 1

In [ ]:
import requests
import pandas as pd

class ScriptData:
    def __init__(self):
        self.api_key = "9H5W499KUM6FLCG1"
        self.data = {}
    
    def fetch_intraday_data(self, script):
        url = f"https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol={script}&interval=60min&apikey={self.api_key}"
        print(url)
        response = requests.get(url)
        self.data[script] = response.json()
    
    def convert_intraday_data(self, script):
        if script not in self.data:
            raise ValueError(f"Data for script '{script}' not found. Please fetch data using the 'fetch_intraday_data' method.")
        time_series = self.data[script]["Time Series (60min)"]
        data = []
        for timestamp, values in time_series.items():
            data.append([pd.Timestamp(timestamp), float(values["1. open"]), float(values["2. high"]), 
                         float(values["3. low"]), float(values["4. close"]), int(values["5. volume"])])
        self.data[script] = pd.DataFrame(data, columns=["timestamp", "open", "high", "low", "close", "volume"])
    
    def __getitem__(self, script):
        if script not in self.data:
            raise ValueError(f"Data for script '{script}' not found. Please fetch and convert data using the 'fetch_intraday_data' and 'convert_intraday_data' methods.")
        return self.data[script]
    
    def __setitem__(self, script, df):
        self.data[script] = df
    
    def __contains__(self, script):
        return script in self.data

### # Calling and using the functionality of ScriptData Class

In [ ]:
# api_key = "9H5W499KUM6FLCG1"  # this is the generated api key using APLHA VANTAGE
script_data = ScriptData() # creating the object for the class ScriptData()

In [ ]:
# Fetch intraday data for a script
script_data.fetch_intraday_data("GOOGL")
# Convert fetched intraday data to a pandas DataFrame
script_data.convert_intraday_data("GOOGL")
# Access the data for a script
script_data["GOOGL"]

https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=GOOGL&interval=60min&apikey=9H5W499KUM6FLCG1

             timestamp    open     high       low     close   volume
0  2023-02-14 20:00:00   94.45   94.500   93.5000   94.1200    54959
1  2023-02-14 19:00:00   94.36   94.490   94.2600   94.3600    39048
2  2023-02-14 18:00:00   94.38   94.400   94.3257   94.4000    71012
3  2023-02-14 17:00:00   94.69   94.690   94.3200   94.3799  1831662
4  2023-02-14 16:00:00   94.16   94.845   93.7900   94.6300  9727151
..                 ...     ...      ...       ...       ...      ...
95 2023-02-07 05:00:00  103.01  104.000  103.0100  103.7000    44939
96 2023-02-06 20:00:00  103.33  103.340  103.0000  103.1600    18062
97 2023-02-06 19:00:00  102.89  103.340  102.8200  103.3400    24482
98 2023-02-06 18:00:00  102.76  102.900  102.7302  102.8055    13778
99 2023-02-06 17:00:00  102.90  103.170  102.5000  102.7300   684025

[100 rows x 6 columns]

In [ ]:
# Fetch intraday data for a script
script_data.fetch_intraday_data("AAPL")
# Convert fetched intraday data to a pandas DataFrame
script_data.convert_intraday_data("AAPL")
# Access the data for a script
script_data["AAPL"]

https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=AAPL&interval=60min&apikey=9H5W499KUM6FLCG1

             timestamp      open      high       low     close   volume
0  2023-02-14 20:00:00  153.0800  153.0900  152.7000  152.8400    52909
1  2023-02-14 19:00:00  153.2000  153.2000  153.0600  153.0900    40175
2  2023-02-14 18:00:00  153.0800  153.2000  153.0166  153.1800   259770
3  2023-02-14 17:00:00  153.2000  153.2000  152.8500  153.0900  2612717
4  2023-02-14 16:00:00  153.2450  153.7300  152.9499  153.1000  7334349
..                 ...       ...       ...       ...       ...      ...
95 2023-02-07 05:00:00  151.5592  151.8587  151.4393  151.7289    47532
96 2023-02-06 20:00:00  151.5891  151.7688  151.5891  151.7489    48037
97 2023-02-06 19:00:00  151.4493  151.6590  151.4094  151.5092    45780
98 2023-02-06 18:00:00  151.4393  151.4993  151.3994  151.4693    28128
99 2023-02-06 17:00:00  151.4993  151.7988  151.3495  151.4194  4683167

[100 rows x 6 columns]

In [ ]:
'GOOGL' in script_data # checking wheter 'GOOGL' is in script_data

True

In [ ]:
'AAPL' in script_data # checking wheter 'AAPL' is in script_data

True

In [ ]:
'NVDA' in script_data # checking wheter 'NVDA' is in script_data

False

__________________________________________

**2.**Define a function called indicator1. It should take “df” and ‘timeperiod’ (integer) as inputs and give another pandas DataFrame as an output with two columns:

**a. timestamp:** Same as ‘timestamp’ column in ‘df’

**b. indicator:** Moving Average of the ‘close’ column in ‘df’. The number of
elements to be taken for a moving average is defined by ‘timeperiod’. 

For example, if ‘timeperiod’ is 5, then each row in this column will be an average
of total 5 previous values (including current value) of the ‘close’ column.

________________________________________________________________________________

### # Function declartion for indicator1

In [ ]:
def indicator1(df, timeperiod):
    df['indicator'] = df['close'].rolling(window=timeperiod).mean()
    return df[['timestamp', 'indicator']]

### # Query : 2. a

In [ ]:
indicator1(script_data['GOOGL'],timeperiod=5)  # calling the function indicator1 for 'GOOGL'

             timestamp  indicator
0  2023-02-14 20:00:00        NaN
1  2023-02-14 19:00:00        NaN
2  2023-02-14 18:00:00        NaN
3  2023-02-14 17:00:00        NaN
4  2023-02-14 16:00:00   94.37798
..                 ...        ...
95 2023-02-07 05:00:00  103.53200
96 2023-02-06 20:00:00  103.50600
97 2023-02-06 19:00:00  103.41400
98 2023-02-06 18:00:00  103.26510
99 2023-02-06 17:00:00  103.14710

[100 rows x 2 columns]

### # Query : 2. b

In [ ]:
indicator1(script_data['AAPL'],timeperiod=5)  # calling the function indicator1 for 'AAPl'

             timestamp  indicator
0  2023-02-14 20:00:00        NaN
1  2023-02-14 19:00:00        NaN
2  2023-02-14 18:00:00        NaN
3  2023-02-14 17:00:00        NaN
4  2023-02-14 16:00:00  153.06000
..                 ...        ...
95 2023-02-07 05:00:00  151.49326
96 2023-02-06 20:00:00  151.61508
97 2023-02-06 19:00:00  151.57314
98 2023-02-06 18:00:00  151.58512
99 2023-02-06 17:00:00  151.57514

[100 rows x 2 columns]

________________________________________________________________________________

**3.**Define a class Strategy, which can do the following, given a script name:

a. Fetch intraday historical day (‘df’) using ScriptData class.
We’ll refer to the ‘close’ column of ‘df’ as close_data.

b. Compute indicator data on ‘close’ of ‘df’ using indicator1 function.
We’ll refer to the ‘indicator’ column of this data as indicator_data.

c. Generate a pandas DataFrame called ‘signals’ with 2 columns:

i. ‘timestamp’: Same as ‘timestamp’ column in ‘df’

ii. ‘signal’: This column can have the following values:

1. BUY (When: If indicator_data cuts close_data upwards)

2. SELL (When: If indicator_data cuts close_data downwards)

3. NO_SIGNAL (When: If indicator_data and close_data don’t cut
each other)
4. Print the ‘signals’ DataFrame with only those rows where the signal is either
‘BUY’ or ‘SELL’.


________________________________________________________________________________

### # Query 3 a

In [ ]:
# query 'a' part
script_data.fetch_intraday_data('NVDA')
script_data.convert_intraday_data('NVDA')
df = script_data['NVDA']
df.rename(columns={'close':'close_data'},inplace=True)
df

https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=NVDA&interval=60min&apikey=9H5W499KUM6FLCG1

             timestamp    open     high       low  close_data   volume
0  2023-02-14 20:00:00  228.50  228.700  228.0600      228.43    80231
1  2023-02-14 19:00:00  229.34  229.440  228.3600      228.50    57164
2  2023-02-14 18:00:00  228.60  229.470  228.3055      229.30   149133
3  2023-02-14 17:00:00  229.71  229.920  227.5200      228.60   722750
4  2023-02-14 16:00:00  229.17  230.488  227.9001      229.60  8519417
..                 ...     ...      ...       ...         ...      ...
95 2023-02-07 05:00:00  211.93  215.290  211.1200      215.04    89990
96 2023-02-06 20:00:00  211.70  212.330  211.4500      212.20    37583
97 2023-02-06 19:00:00  211.10  211.850  211.0500      211.75    21096
98 2023-02-06 18:00:00  211.00  211.120  210.8900      211.10    17864
99 2023-02-06 17:00:00  210.89  211.140  210.5200      211.05   601100

[100 rows x 6 columns]

### # Query 3 b

In [ ]:
# here we have change the close cloumn so we need to change the indicator1 function
def updated_indicator1(df, timeperiod):
    df['indicator'] = df['close_data'].rolling(window=timeperiod).mean()  # here we have to use 'close_data' instead of using 'close'
    return df[['timestamp', 'indicator']]

In [ ]:
# query 'b' part
df1 = updated_indicator1(df,timeperiod=5)
df1.rename(columns = {'indicator':'indicator_data'},inplace=True)
df1

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

             timestamp  indicator_data
0  2023-02-14 20:00:00             NaN
1  2023-02-14 19:00:00             NaN
2  2023-02-14 18:00:00             NaN
3  2023-02-14 17:00:00             NaN
4  2023-02-14 16:00:00       228.88600
..                 ...             ...
95 2023-02-07 05:00:00       214.09014
96 2023-02-06 20:00:00       213.87200
97 2023-02-06 19:00:00       213.37400
98 2023-02-06 18:00:00       212.74000
99 2023-02-06 17:00:00       212.22800

[100 rows x 2 columns]

### # Class Strategy

In [ ]:
class Strategy:
    def __init__(self, script_name):
        self.script_name = script_name
        self.df = None
        self.df1 = None
        self.indicator_df = None
        self.signals = None
        self.script_data = ScriptData()
    # creating the scriptdata for close_data
    def fetch_data(self):
      self.script_data.fetch_intraday_data(self.script_name)
      self.script_data.convert_intraday_data(self.script_name)
      self.df = self.script_data[self.script_name]
      self.df.rename(columns={'close':'close_data'},inplace=True)
      # print(self.df)
      return self.df

    # creating indicator data on close of script data
    def indicator1(self,timeperiod=5):
      self.df=self.fetch_data()
      df=self.df
      df['indicator'] = df['close_data'].rolling(window=timeperiod).mean()
      return df[['timestamp', 'indicator']]
    def generate_signals(self, timeperiod):
        self.df1=self.indicator1(timeperiod)
        # print(self.df1)
        signals = []
        for i in range(1, len(self.df)):
            if self.df1['indicator'][i] > self.df['close_data'][i] and self.df1['indicator'][i-1] <= self.df['close_data'][i-1]:
                signals.append('BUY')
            elif self.df1['indicator'][i] < self.df['close_data'][i] and self.df1['indicator'][i-1] >= self.df['close_data'][i-1]:
                signals.append('SELL')
            else:
                signals.append('NO_SIGNAL')
        self.signals = pd.DataFrame({'timestamp': self.df['timestamp'][1:], 'signal': signals})
    
    def print_signals(self):
        # signals_df = self.signals[self.signals['signal'] != 'NO_SIGNAL']
        signals_df = self.signals
        print(signals_df )

### #Query 3 d

In [ ]:
#  d
strategy = Strategy('NVDA')
strategy.generate_signals(5)
strategy.print_signals()

https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=NVDA&interval=60min&apikey=9H5W499KUM6FLCG1
             timestamp     signal
1  2023-02-14 19:00:00  NO_SIGNAL
2  2023-02-14 18:00:00  NO_SIGNAL
3  2023-02-14 17:00:00  NO_SIGNAL
4  2023-02-14 16:00:00  NO_SIGNAL
5  2023-02-14 15:00:00  NO_SIGNAL
..                 ...        ...
95 2023-02-07 05:00:00       SELL
96 2023-02-06 20:00:00        BUY
97 2023-02-06 19:00:00  NO_SIGNAL
98 2023-02-06 18:00:00  NO_SIGNAL
99 2023-02-06 17:00:00  NO_SIGNAL

[99 rows x 2 columns]

________________________________________________________________________________

**4.** [OPTIONAL] Plot a candlestick chart of ‘df and ‘indicator’. You can use
‘pyalgotrading’ to do so. The chart will look like this.
________________________________________________________________________________

In [ ]:
script_data = ScriptData()
# Fetch intraday data for a script
script_data.fetch_intraday_data("GOOGL")
# Convert fetched intraday data to a pandas DataFrame
script_data.convert_intraday_data("GOOGL")
# Access the data for a script
pf = script_data["GOOGL"]
pf

https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=GOOGL&interval=60min&apikey=9H5W499KUM6FLCG1

             timestamp    open     high       low     close   volume
0  2023-02-14 20:00:00   94.45   94.500   93.5000   94.1200    54959
1  2023-02-14 19:00:00   94.36   94.490   94.2600   94.3600    39048
2  2023-02-14 18:00:00   94.38   94.400   94.3257   94.4000    71012
3  2023-02-14 17:00:00   94.69   94.690   94.3200   94.3799  1831662
4  2023-02-14 16:00:00   94.16   94.845   93.7900   94.6300  9727151
..                 ...     ...      ...       ...       ...      ...
95 2023-02-07 05:00:00  103.01  104.000  103.0100  103.7000    44939
96 2023-02-06 20:00:00  103.33  103.340  103.0000  103.1600    18062
97 2023-02-06 19:00:00  102.89  103.340  102.8200  103.3400    24482
98 2023-02-06 18:00:00  102.76  102.900  102.7302  102.8055    13778
99 2023-02-06 17:00:00  102.90  103.170  102.5000  102.7300   684025

[100 rows x 6 columns]

### # Candlestick Visualisation

In [ ]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Candlestick(x=pf['timestamp'],open=pf['open'], high=pf['high'],low=pf['low'], close=pf['close'])])
fig.update_layout(xaxis_rangeslider_visible=False)
fig.show()
# this will visualize the candlestick view of the data using plotly

### # Candlestick Visualisation with close and indicator data of timeperiod=5

In [ ]:
import plotly.graph_objects as go
df1=indicator1(pf,timeperiod=5)
fig = go.Figure(
    data=[
       go.Candlestick(
           x=pf['timestamp'],
           open=pf['open'],
           high=pf['high'],
           low=pf['low'],
           close=pf['close'],
           line=dict(width=1),
           name="Historical Data",
       ),
       go.Line(
            x=df1['timestamp'],
            y=df1['indicator'],
            line=dict(width=0.5),
            name="5_SMA",
            line_color='grey',
       ),
       go.Line(
          x=pf['timestamp'],
          y=pf['close'],
          line=dict(width=0.5),
          name='Close',
          line_color='blue',
       ),       
    ]
)
fig.show()

/usr/local/lib/python3.8/dist-packages/plotly/graph_objs/_deprecations.py:378: DeprecationWarning:

plotly.graph_objs.Line is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Line
  - plotly.graph_objs.layout.shape.Line
  - etc.

In [ ]:
# Abhilash Gaurav
# Algobulls Internship assessment

________________________________________________________________________________